### ISSUE TITLE
Diffex improvements: final steps to be done

### ISSUE THREAD

**Issue by blrnw3** [chanzuckerberg/single-cell-explorer#235]
Revised plan to pull out separate work-streams.

*NOTE:* dependencies are explicitly declared (eg, item 2 is dependent on item 1, and items 2,3,4, and 5 can be done in parallel).

1. Resolve possibly blocking tiledb bugs:
    - [X] Dependency: none
    - [X] Owner: @bkmartinjr 
    - [X] TileDB 0.13.1 dense read bug.  Workaround inserted into PR #237. Expect fix in 0.13.2
    - [x] expensive list cast of the ndarray in the dense read - see  
    https://github.com/chanzuckerberg/single-cell-explorer/pull/234#discussion_r826228256.    Test case reported to TileDB, and fix expected in 0.13.2.  Work-around is currently in place.

3. CXG Schema Update - goal: peformance tune the CXG X schema
    - [x] Dependency unblocked:  item 1
    - [ ] Owner: @ebezzi  
    - [x] Add TiledB dense issue workaround to data portal.  Add `{"sm.query.dense.reader": "legacy"}` to the TileDB context used for reading/writing *dense* arrays (has no effect on sparse read/write)  **OBSOLETE** with tiledb update.
    - [x] Confirm with Bruce that CXG schema is finalized (there are some divergences from original recommendations that need to be verified).
    - [ ] Finish and land changes to the [Data Portal PR \#2119](chanzuckerberg/single-cell-data-portal#2119) and merge it.
    - [ ] Create script to upgrade all legacy CXGs, which would wrap [this cxg_remaster.py script](https://github.com/chanzuckerberg/single-cell-data-portal/blob/83b0ead5252304ec812808d1d08134bdb16209e5/scripts/cxg_remaster.py) (part of DP PR 2119 above).  In principle, the steps are, for all CXGs:
        1. backup existing X array for all CXGs
        2. create X_new using above script
        4. swap the X arrays (X_new becomes X; X is deleted)
    - [ ] Convert all legacy CXGs.  For each environment, suggest using an adhoc c6i.32xlarge w read/write S3 perms to the bucket.  After each step, verify Explorer still works well on a small sample of the converted CXGs.
        - [ ] Run conversion script on all legacy CXGs in DEV. 
        - [ ] run conversion script on all legacy CXGs in Staging.
        - [ ] run conversion script on all legacy CXGs in PROD
        - See detailed plan [here](https://docs.google.com/document/d/1uSC4STAHUSZfoCs6junsduN9DVPb5bQfEsBpChFKAUY/edit#).

3. Diffex algo tuning in Explorer - goal: faster diffex compute in explorer backend.
    - [x] Dependency unblocked:  item 1
    - [X] Owner: @bkmartinjr     
    - [x] PR finished #234
    - [ ] PR #234 reviewed & landed

5. update deployment instance type and CDN config
    - [X] Dependency unblocked: none
    - [ ] Owner: @atolopko-czi 
    - [ ] finalize instance type.  *Note:* Bruce has benchmark results that suggests we could deploy something smaller than a c6i.32xlarge (perhaps c6i.16xlarge).
    - [ ] define HA policy for Dev & Staging and add to [Infra PR #526](https://github.com/chanzuckerberg/single-cell-infra/pull/526).  In particular, why have redundant (HA) config for dev & staging given the $$ impact?
    - [ ] Update Explorer backend config to match instance characteristics.  Specifically: tile cache and python query buffer values are dependent on instance RAM.
    - [ ] Increase the connection read timeouts from 30s to 60s.  This requires changes to CloudFront and LB.
    - [ ] Finish & merge [Infra PR #526](https://github.com/chanzuckerberg/single-cell-infra/pull/525)

6. Integrate new diffex postings list encoding into explorer f/e and b/e.
    - [X] Dependency unblocked: none
    - [X] Owner: @bkmartinjr 
    - [x] PR ready and out for review (#244)
    - [ ] PR reviewed & landed
  
7. System and performance test
    - [ ] Dependency unblocked: 1, 2, 3, 4, 5
    - [X] Owner: @bkmartinjr 
    - [ ] Synthetic CLI benchmark (ie, not using front-end) to verify that b/e perf is as expected.

8. Deploy diffexp limit update:
    - [ ] Dependency unblocked: 6
    - [ ] Owner: @atolopko-czi 
    - [ ] Merge [Infra PR #525](https://github.com/chanzuckerberg/single-cell-infra/pull/525)

9. Analytics support
    - [ ] Dependency unblocked: items 7, 8
    - [ ] Owner: @tihuan 
    - [ ] PR - adding the Plausible tags so that our UXR team can also observe the usage of differential expression

10. Remove tiledb 0.13.1 work-arounds
    - [x] Dependency unblocked: TileDB 0.13.2 shipped and fixes verified.
    - [x] Owner: @bkmartinjr 

-----

## Ben's original notes for context

Apologies that I couldn't finish off this work. Here are the remaining steps as I see them

# Steps to do, in order

1. Apply Bruce’s new encoding scheme to the diffex routes in Explorer
   * Bruce has context on this
1. Investigate probable tiledb 0.13 bug - see [this PR description](https://github.com/chanzuckerberg/single-cell-explorer/pull/234). This may be the same bug that the WMG team is facing. It needs fixing before proceeding with any of the following
    * Update: this is not the same bug as WMG found. It is a bug that only affects _dense_ array reading.  Workaround is to set the config option: `{"sm.query.dense.reader": "legacy"}`  
    * TileDB expects to have an released fix in their next release (2 weeks)
    * PR #237 bumps tiledb version and inserts workaround (and a test case to validate)
1. Investigate second tiledb bug which requires an expensive list cast of the ndarray in the dense read - see comment in the explorer PR below
1. Merge infra PRs
   1. https://github.com/chanzuckerberg/single-cell-infra/pull/526
   1. https://github.com/chanzuckerberg/single-cell-infra/pull/525
1. [Merge data portal PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/2119)
1. [Merge Explorer PR](https://github.com/chanzuckerberg/single-cell-explorer/pull/234)
1. Use [this cxg_remaster.py script](https://github.com/chanzuckerberg/single-cell-data-portal/blob/83b0ead5252304ec812808d1d08134bdb16209e5/scripts/cxg_remaster.py) (part of DP PR above) to update all staging CXGs to the optimized tiledb schema
   1. Use an adhoc c6i.32xlarge w read/write S3 perms to the bucket 
   1. I've tested the script in staging but only converted a few of them. It should just be able to run to completion on its own though, once you start it
   1. The final step is to swap all the X_new remastered arrays over to X (backup X as X_old first). This should likely be scripted out
1. Once explorer changes are in staging, test them. Diffex on 1.5M cells should take <20s if using a c6i.32xlarge (pick the biggest dataset that will load)
1. Repeat steps 7-8 for prod

Cooldown story: add feature-level [analytics support](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1631) so we can gather metrics on diffex usage

**Comment by blrnw3** [comment]
@maniarathi here's the remaining diffex work. I tagged all our tiledb experts and will defer to the team to see who gets to privilege of doing the work :D.
Thanks everyone

**Comment by atolopko-czi** [comment]
> @maniarathi here's the remaining diffex work. I tagged all our tiledb experts and will defer to the team to see who gets the privilege of doing the work :D. Thanks everyone

Thanks @blrnw3! 👋

**Comment by maniarathi** [comment]
@blrnw3 Thank you!

**Comment by bkmartinjr** [comment]
@atolopko-czi @maniarathi - could you review the revised plan, and add owners/tasks/etc?

Please note the parallelism possible. Much of the remaining work can occur in parallel.

**Comment by maniarathi** [comment]
@atolopko-czi @metakuni @tihuan , I have made a suggestion on how to split up the work. Let me know if this looks OK to you.

**Comment by bkmartinjr** [comment]
> @atolopko-czi @metakuni @tihuan , I have made a suggestion on how to split up the work. Let me know if this looks OK to you.

Related:  item one is complete, so the work for items 2, 3, 4, and 5 are unblocked.

**Comment by tihuan** [comment]
For item 8 analytics support, do we know what we want to track already or still need to define that? 

Thank you!

**Comment by bkmartinjr** [comment]
> For item 8 analytics support, do we know what we want to track already or still need to define that?

CC: @maniarathi - I believe you added this.  Is there a spec?

@tihuan - if not, I suggest we keep it simple:
* dataset ID
* num cells in selection set
* time to complete (from f/e perspective)
* success/failure (ie, 200 response or not)

**Comment by tihuan** [comment]
Sounds great thank you! I'm thinking maybe if those can be tracked in BE it'll be more reliable. Unless some of the info is only available in FE?

**Comment by tihuan** [comment]
Thanks @maniarathi ! Plausible tags to record the metrics Bruce mentioned [above](https://github.com/chanzuckerberg/single-cell-explorer/issues/235#issuecomment-1092180950) or something else?

Plausible also allows sending events [from the server](https://plausible.io/docs/events-api) for reliable tracking 🙆‍♂️

**Comment by bkmartinjr** [comment]
I recommend client-side events as this allows the capture of failures and end-to-end timing as well.  We will be blind to many of those without doing this on the client-side.
