### ISSUE TITLE
Upgrade Explorer to Python 3.10

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-explorer#564]
## Motivation

Language features availability, performance, security.

Secondarily, TileDB Mac M1/arm builds are available for Py 3.10+, which avoids a lengthy compilation process for Mac M1 users.

## Definition of Done

Explorer runs w/o issue on 3.10

## Tasks

- [ ] Docker containers updated
- [ ] Linters updated (to check against 3.10 compliance)
- [ ] Documentation updated
- [ ] Full system testing performed on rdev
